- name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
  uses: docker/login-action@v1.14.1
  with:
    # Server address of Docker registry. If not set then will default to Docker Hub
    registry: pilgrima
    # Username used to log against the Docker registry
    username: pilgrima
    # Password or personal access token used to log against the Docker registry
    password: xl5254382
    # Specifies whether the given registry is ECR (auto, true or false)
    ecr: # optional, default is auto
    # Log out from the Docker registry at the end of a job
    logout: # optional, default is true
    
- name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd glibc_jdk8 && docker build . --file Dockerfile --tag pilgrima/jdk8:$(date +%s) && docekr push pilgrima/jdk8:$(date +%s)

